version: '3' 
services: 
  web: 
    build:
      context: .
    command: 'python3 run.py'
    ports: 
      - '5000:5000'
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  worker:
    build: 
      context: .
    command: 'rq worker -u redis://redis:6379/0 background-job'
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"